### ISSUE TITLE
Unbox Fail on starting unbox  step  due to   bash unbox.sh && rm unbox.sh

### ISSUE THREAD

**Issue by technqvi** [smartcontractkit/truffle-starter-kit#100] opened 2021-05-24 04:39 UTC
Hi 

I follow your tutorial to create Truffle project with  truffle-starter-kit  [Truffle, Hardhat, and Defi - Chainlink Hackathon Workshop](https://www.youtube.com/watch?v=xNpzWaRaHfM).

I cannot continue doing any next steps due to  Unbox failed as the figure shown below.
 
My environment are belows.
1. Window 10  enterprise
2. Visual studion code , use cmd as terminal
3.  Node.js 14.17
4. Truffle  5.3.7
5. Already git app, ghit  bash

![image](https://user-images.githubusercontent.com/38780060/119297231-c31b8e00-bc84-11eb-98ad-2b0675041b3f.png)

![image](https://user-images.githubusercontent.com/38780060/119297014-4c7e9080-bc84-11eb-8d20-73241061a309.png)

**Comment by pappas999** [comment] 2021-05-26 00:15
thanks for raising this @technqvi . I'll try to reproduce and report back

**Comment by pappas999** [comment] 2021-05-26 01:39
Hi @technqvi , do you have additional logging that you can share? If it's a long file you can upload it. It might help us debug the issue easier.

Anyway looks like others are having similar issues, I think it could possibly be versions of npm or nodejs you're running. Can you try some of the suggestions in [this thread](https://github.com/trufflesuite/truffle/issues/3860) and let me know how you go? Ie try installing an older version of nodejs like 10 or 12

**Comment by technqvi** [comment] 2021-05-26 16:59
I try to downgrade node.js to be 12, the error still arises.

This is a screenshot for this error.
![image](https://user-images.githubusercontent.com/38780060/119701197-48b65e00-be7e-11eb-9c79-6eed803e2178.png)

**Comment by pappas999** [comment] 2021-05-27 03:02
Thanks for trying that. Can I ask that you try to unbox another truffle box, eg  [Truffle React](https://www.trufflesuite.com/boxes/react)

If you get the same error then it's likely some sort of config or setup issue with Truffle or your environment, as opposed to an issue specifically with the Chainlink Truffle Box. And if this is the case, suggest raising your issue on the [Truffle GitHub](https://github.com/trufflesuite/truffle/issues), to get the help you need. 

If you can unbox other boxes successfully, and your issue is specifically with the Chainlink box, let me know here and we'll move forward

**Comment by technqvi** [comment] 2021-05-27 15:01
> Thanks for trying that. Can I ask that you try to unbox another truffle box, eg [Truffle React](https://www.trufflesuite.com/boxes/react)
> 
> If you get the same error then it's likely some sort of config or setup issue with Truffle or your environment, as opposed to an issue specifically with the Chainlink Truffle Box. And if this is the case, suggest raising your issue on the [Truffle GitHub](https://github.com/trufflesuite/truffle/issues), to get the help you need.
> 
> If you can unbox other boxes successfully, and your issue is specifically with the Chainlink box, let me know here and we'll move forward

I spent some time on trying to unbox several truffle templates as your suggestion.  I found something remarkable in what I've done.

**_### The following boxes , I got things done.
npx truffle unbox drizzle
truffle unbox pet-shop
truffle unbox vyper-example
npx truffle unbox react
truffle unbox vue-box
truffle unbox metacoin
npx truffle unbox webpack
truffle unbox tutorialtoken
truffle unbox blueprint_**
<img width="1090" alt="success" src="https://user-images.githubusercontent.com/38780060/119846533-6c3be000-bf34-11eb-813d-77c25218055a.png">


### **_Instead, The following boxes, I cannot unbox completely.    I notice that all paths of these boxes are like    sub-directory.
 xxxx/box_template_**

truffle unbox adrianmcli/truffle-next
npx truffle unbox rsksmart/rsk-react-box
truffle unbox aave/flashloan-box
truffle unbox DOkwufulueze/eth-vue

Almost all o them occurred error at step2 (downloading) but end up with success, you can see in the figure below.
except  **truffle unbox DOkwufulueze/eth-vue and truffle unbox smartcontractkit/box**   both occured error in step# 4 (setting ubox). Nevertheless. I can still run commands following Patrcik 's tutorial without any problems.
[https://www.youtube.com/watch?v=xNpzWaRaHfM](url)

**### I am wondering that,  I can keep developing on any unboxed projects regardless of whether unboxing is completed or not?**

Lastly, Please recommend link to download template if  I use python-brownie , I am good at Python

<img width="688" alt="failed" src="https://user-images.githubusercontent.com/38780060/119846549-7067fd80-bf34-11eb-9aec-08490ee27671.png">

**Comment by pappas999** [comment] 2021-05-28 01:39
Good to hear you can still use the box despite the error. Definitely a weird one. We'll take a closer look at it and try to replicate on a windows machine.

If you are good with Python, suggest checking out our [Brownie Starter Kit](https://github.com/smartcontractkit/chainlink-mix). 

If you build a working contract example, feel free to share it with everyone by contributing to our [Starer Kit Showcase](https://blog.chain.link/starter-kit-showcase/) initiative currently running. You can do this be posting it in our [discord](https://discord.gg/nPmjK56j) in the #starter-kit-showcase channel, or on twitter with the #StarterKitShowcase tag!

**Comment by technqvi** [comment] 2021-05-28 03:36
> Good to hear you can still use the box despite the error. Definitely a weird one. We'll take a closer look at it and try to replicate on a windows machine.
> 
> If you are good with Python, suggest checking out our [Brownie Starter Kit](https://github.com/smartcontractkit/chainlink-mix).
> 
> If you build a working contract example, feel free to share it with everyone by contributing to our [Starer Kit Showcase](https://blog.chain.link/starter-kit-showcase/) initiative currently running. You can do this be posting it in our [discord](https://discord.gg/nPmjK56j) in the #starter-kit-showcase channel, or on twitter with the #StarterKitShowcase tag!

Ok

**Comment by PatrickAlphaC** [comment] 2021-06-28 02:47
Closing for now

**Closed by PatrickAlphaC** 2021-06-28 02:47 UTC
